/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCategory: typeof import('./src/components/Category/AddCategory.vue')['default']
    BarcodeIcon: typeof import('./src/components/icons/BarcodeIcon.vue')['default']
    BottomNavigationBar: typeof import('./src/components/BottomNavigationBar.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Categories: typeof import('./src/components/Category/Categories.vue')['default']
    Category: typeof import('./src/components/Category/Category.vue')['default']
    CustomErrorMessage: typeof import('./src/components/FormComponent/CustomErrorMessage.vue')['default']
    CustomInput: typeof import('./src/components/FormComponent/CustomInput.vue')['default']
    DeletePopup: typeof import('./src/components/DeletePopup.vue')['default']
    ExpensesCard: typeof import('./src/components/Expenses/ExpensesCard.vue')['default']
    ExpensesForm: typeof import('./src/components/Expenses/ExpensesForm.vue')['default']
    ExpensesSkeleton: typeof import('./src/components/Expenses/ExpensesSkeleton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InventoryIcon: typeof import('./src/components/icons/InventoryIcon.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    NoReportsDisplay: typeof import('./src/components/Reports/NoReportsDisplay.vue')['default']
    PasswordInput: typeof import('./src/components/FormComponent/PasswordInput.vue')['default']
    PrimaryButton: typeof import('./src/components/Buttons/PrimaryButton.vue')['default']
    Product: typeof import('./src/components/Product/Product.vue')['default']
    ProductCategoryIcon: typeof import('./src/components/icons/ProductCategoryIcon.vue')['default']
    Products: typeof import('./src/components/Product/Products.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanIcon: typeof import('./src/components/icons/ScanIcon.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    SecondaryButton: typeof import('./src/components/Buttons/SecondaryButton.vue')['default']
    SkeletonLoading: typeof import('./src/components/SkeletonLoading.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    UnderDevelopment: typeof import('./src/components/UnderDevelopment.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
